[package]
name = "fast_log"
version = "1.1.1"
description = "Rust async log 高性能异步日志"
readme = "Readme.md"
authors = ["ce <zhuxiujia@qq.com>"]
edition = "2018"
license = "MIT"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = {version =  "0.4",features = ["std"] }
tokio = { version = "0.2", features = ["full"] }
async-std = "1.6.1"
